name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here...

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Android
        - iOS
        - macOS
        - Windows
        - Linux
        - Web
    validations:
      required: true

  - type: input
    id: flutter-version
    attributes:
      label: Flutter Version
      description: Run `flutter --version` to get this information
      placeholder: e.g., Flutter 3.5.4
    validations:
      required: true

  - type: input
    id: dart-version
    attributes:
      label: Dart Version
      description: Run `dart --version` to get this information
      placeholder: e.g., Dart 3.2.0
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device Information
      description: Device model and OS version
      placeholder: e.g., iPhone 14 Pro (iOS 17.0) or Pixel 7 (Android 13)

  - type: input
    id: opencode-version
    attributes:
      label: OpenCode Server Version
      description: Version of the OpenCode server you're connecting to
      placeholder: e.g., 1.2.3

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I am using the latest version of the app
          required: false